#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Android Studio.
##
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

APP_HOME=`cd "$(dirname "$0")" && pwd`

OS=`uname`
case $OS in
  Darwin*) darwin=true ;;
  Linux*) linux=true ;;
  MINGW*|MSYS*|CYGWIN*) cygwin=true ;;
  *) ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -r "$CLASSPATH" ]; then
    die "ERROR: Could not find $CLASSPATH"
fi

JAVA_CMD="java"
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVA_CMD="$JAVA_HOME/jre/sh/java"
    else
        JAVA_CMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVA_CMD" ] ; then
        warn "WARN: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
        JAVA_CMD="java"
    fi
fi

exec "$JAVA_CMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
